name: CI

on:
  push:
    branches:
      - main
  release:
    types:
      - prereleased
      - published
  workflow_dispatch:

jobs:
  matrix-coverage:
    uses: scikit-package/release-scripts/.github/workflows/_matrix-and-codecov-on-merge-to-main.yml@v0
    with:
      project: diffpy.cmi
      c_extension: false
      headless: false
      run: |
        set -Eeuo pipefail
        echo "Test cmds"
        cmi -h
        cmi env
        cmi pack list
        cmi profile list
        cmi install plotting
        if [ "${RUNNER_OS}" != "Windows" ]; then
          conda list | grep -i ipympl
        else
          source "$(cygpath -u "$CONDA")/etc/profile.d/conda.sh"
          conda activate test
          conda list | grep -i ipympl
        fi

        echo "Running tests for diffpy.cmi dependencies"
        cmi install _tests
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
