name: Run Example Scripts

on:
  workflow_dispatch:

jobs:
  run-examples:
    uses: scikit-package/release-scripts/.github/workflows/_tests-on-pr.yml@v0
    with:
      project: diffpy.cmi
      c_extension: false
      headless: false
      run: |
        set -Eeuo pipefail
        echo "Running example scripts"
        pytest --cov tests/test_examples.py -v
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
