name: Tests on PR

on:
  pull_request:
  workflow_dispatch:

jobs:
  tests-on-pr:
    uses: scikit-package/release-scripts/.github/workflows/_tests-on-pr.yml@v0
    with:
      project: diffpy.cmi
      c_extension: false
      headless: false
      run: |
        echo "Running tests for diffpy.cmi"
        cmi install _tests
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
