name: Test PDF Pack Scripts

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  test-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Initialize Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: test
          channels: conda-forge
          python-version: 3.13
          auto-activate-base: false

      - name: Configure Conda
        run: |
          conda config --set always_yes yes --set changeps1 no

      - name: Install dependencies
        run: |
          conda install -y matplotlib diffpy.cmi
          conda install --file requirements/packs/core.txt -y
          conda install --file requirements/packs/docs.txt -y
          conda install --file requirements/packs/pdf.txt -y
          conda install --file requirements/packs/plotting.txt -y
          conda install --file requirements/packs/tests.txt -y

      - name: List Installed Packages
        run: conda list

      - name: Run diffpy.cmi scripts
        shell: bash -l {0}
        run: |
          set -e
          export MPLBACKEND=Agg
          for script in docs/examples/ch*/solutions/diffpy-cmi/*.py; do
            echo "Running $script..."
            python "$script"
          done
