name: Tests on PR push

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  fast-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Check out diffpy.cmi
        uses: actions/checkout@v4

      - name: Initialize miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: test
          channels: conda-forge
          auto-update-conda: true
          auto-activate-base: false
          python-version: 3.13

      - name: Conda config
        run: conda config --set always_yes yes --set changeps1 no

      - name: Install dependencies
        run: |
          conda install --file requirements/conda.txt
          conda install --file requirements/tests.txt
          python -m pip install . --no-deps

      - name: Run extra CLI commands
        run: |
          set -Eeuo pipefail
          cmi -h
          cmi env
          cmi pack list
          cmi profile list
          cmi install plotting

      - name: Quick tests (subpackages + Ni example)
        run: |
          FAST_EXAMPLES=1 pytest --cov

      - name: Coverage report
        run: coverage report -m

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          verbose: true
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
